nelmio_api_doc:
    documentation:
        info:
            title: API documentation
            description: This is an awesome app!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/articles # Accepts routes under /api except /api/doc
